### ISSUE TITLE
License

### ISSUE THREAD

**Issue by senceryazici** [asukiaaa/BLVD20KM_asukiaaa#1]
I'm interested in your work and I'll be using it. But For MIT licenses you must include a LICENSE file containing the license text and the copyright notice, including date and your name, so I can copy that license text and copyright notice in my own copy.

Thanks.

**Comment by asukiaaa** [comment]
Sorry for no response.
I add a file about license.
https://github.com/asukiaaa/BLVD20KM_asukiaaa/commit/812baef2c28f7b8753a576c74d158833fdd41c0a

**Comment by senceryazici** [comment]
Thanks
