### ISSUE TITLE
Can't find DI, RO, RE, DE pins in the RS-485 transceiver card

### ISSUE THREAD

**Issue by WsssM** [asukiaaa/BLVD20KM_asukiaaa#2]
Hello,
     I read your tutorial here which I carefully followed
     Only communication between Arduino MEGA 2560 and BLVD20KM inverter still not working.
     To start I bought the following card as in the tutorial : https://www.sparkfun.com/products/10124
     And I can't find the DI, RO, RE, DE pins in it? how do I connect them?
     Thank you in advance for your precious help.
Sincerely,

**Comment by asukiaaa** [comment]
> https://www.sparkfun.com/products/10124
> And I can't find the DI, RO, RE, DE pins in it? how do I connect them?

The module has a pin that is connected to DE and RE.
Pin4 of the module is that.
https://cdn.sparkfun.com/datasheets/BreakoutBoards/RS485_Breakout_v10.pdf

![Screenshot from 2021-11-26 10-05-56](https://user-images.githubusercontent.com/5975178/143729310-44704534-f94a-4ae4-be05-bbe258fd58ee.png)
So you can use my library like this.

```cpp
#define RS485_DE 4 // some pin that you want to use for toggling de and re
#define RS485_RE RS485_DE
#define MOTOR_ADDRESS 0 // 0 for udp

BLVD20KM_asukiaaa motor(&Serial1, MOTOR_ADDRESS, RS485_DE, RS485_RE);
```

**Comment by asukiaaa** [comment]
In conclusion

Connect like this as I mentioned in https://github.com/asukiaaa/BLVD20KM_asukiaaa/issues/3.
Arduino | RS485 module
--- | ---
5V | pin1 VCC
TX1 | pin2 RX-I
RX1 | pin3 TX-O
D4 | pin4 RTX
GND | GND

Can you close this issue?

**Comment by WsssM** [comment]
I make a small modification on the TX / RX and I add a little more details: :

**BLVD20KM driver LAN Cable  <-> SparkFun Transceiver Breakout - RS-485 :**
<html>
<body>


BLVD20KM driver LAN Cable | SparkFun Transceiver Breakout - RS-485
-- | --
LAN6 (Green) | B
LAN3 (White Green) | A
LAN2 (Orange) | G

**Arduino <-> SparkFun Transceiver Breakout - RS-485 :**
No | Role
-- | --
5V | 3-5V pin
RX1 | RX-I pin
TX1 | TX-O pin
D4 | RTS pin
GND |  pinGND

</body>
</html>



and it works with that 👍, thanks again

![IMG_20211205_221709](https://user-images.githubusercontent.com/68170072/144764284-a2b8c2dd-001f-4179-bd82-eb35e9eb7846.jpg)

**Comment by asukiaaa** [comment]
Thank you for sum up and close the issue.

> RX1 | RX-I pin
> TX1 | TX-O pin

Are they correct?
I think that RX should connect to TX.

**Comment by WsssM** [comment]
Yes, the correct wiring is ;
RX1 | RX-I pin
TX1 | TX-O pin
And if I reverse them everything stops without red light or alarm light

**Comment by asukiaaa** [comment]
Mm.. it seems strange but I see any way.
It's OK if you can communicate with the motor driver.
