### ISSUE TITLE
How to get feedback speed

### ISSUE THREAD

**Issue by kamon2022** [asukiaaa/BLVD20KM_asukiaaa#4]
Hello.

I want to ask you about feedback speed. 

In code arduino, 

motorA.writeSpeed(500);
  motorA.writeForward();
  readAndPrintSpeed("motorA", &motorA);
 
  
  
  ->  readAndPrintSpeed("motorA", &motorA);  
  I think this line is not feedback speed. It is command speed. 
  For example, if I set [motorA.writeSpeed(500);]  
  Motor speed is 500; 
  
  Could you tell me how to get feedback speed ?
![code](https://user-images.githubusercontent.com/99008193/155065811-6f5cfa67-d943-42cd-b4d8-72d6794fed36.jpg)

**Comment by asukiaaa** [comment]
Use `readFeebackSpeed`.
https://github.com/asukiaaa/BLVD20KM_asukiaaa/blob/master/src/BLVD20KM_asukiaaa.h#L55

**Comment by kamon2022** [comment]
Thank you very much. 

I have more question. Can I control position of motor ?
For example, I want to rotate 720 degree. Can I control to rotate 720 degree ?

**Comment by kamon2022** [comment]
> Use `readFeebackSpeed`. https://github.com/asukiaaa/BLVD20KM_asukiaaa/blob/master/src/BLVD20KM_asukiaaa.h#L55

Thank you very much.

I have more question. Can I control position of motor ?
For example, I want to rotate 720 degree. Can I control to rotate 720 degree ?

**Comment by asukiaaa** [comment]
I'm not sure BLVD series have function to get degree or step.
Can you find such functions from datasheet of it?
I'm happy if you support some function, add some method to this library and create pull request.

**Comment by kamon2022** [comment]
> I'm not sure BLVD series have function to get degree or step. Can you find such functions from datasheet of it? I'm happy if you support some function, add some method to this library and create pull request.

OK. I will find step function.
Now I already used with BLVD10KM driver. No problem. It can work for speed.

**Comment by asukiaaa** [comment]
I see.
Can you close this issue?
