### ISSUE TITLE
What is function of writeLock();

### ISSUE THREAD

**Issue by kamon2022** [asukiaaa/BLVD20KM_asukiaaa#5]
Hi. 

I want to ask you about writeLock(); function 
https://github.com/asukiaaa/BLVD20KM_asukiaaa/blob/master/src/BLVD20KM_asukiaaa.h#L55

What is writeLock(); function ?

**Comment by asukiaaa** [comment]
Some BLVD series motor have Electromagnetic Brake. (locking by solenoid)
`writeLock` enables it at stopping.
https://catalog.orientalmotor.com/item/blv-series-brushless-dc-motor-speed-control/400w-blv-series-brushless-dc-motors/blv640nm5s-3

**Comment by asukiaaa** [comment]
No appreciation, who are you?

**Comment by kamon2022** [comment]
> No appreciation, who are you?

Sorry, Thank you very much.
